name: opentrivia
description: A new Flutter project.

version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  flutter_custom_clippers: ^1.1.2
  html_unescape: ^1.0.2
  auto_size_text: ^2.1.0
  lottie: ^0.7.0+1
  circular_countdown_timer: ^0.0.9
  fluttertoast: ^7.1.6
  syncfusion_flutter_gauges: ^18.4.39
  progress_hud: ^1.1.0
  double_back_to_close_app: ^2.0.1
  loading_animations: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300


module:
  androidX: true # Add this line.
